### ISSUE TITLE
empty string converted to 0

### ISSUE THREAD

**Issue by mgkimsal** [Magicalex/WriteIniFile#6]
If a value is an empty string, it's converted to 0, which is generally not what's wanted.

The encode() method would need to be changed.

**Comment by al3xLvs** [comment]
Empty string is properly converted now.
Thanks you for your interest.

You can upgrade to v1.2.1

**Comment by mgkimsal** [comment]
thanks!

was going to look at patching/testing/pr later this afternoon, but you beat me to it.
