### ISSUE TITLE
Linux EOL always used

### ISSUE THREAD

**Issue by betterphp** [Magicalex/WriteIniFile#9]
When writing the .ini file the unix end of line, `\n`, character is always used. This breaks some Windows applications that parse ini files assuming `\r\n` has been used.

In this method https://github.com/Magicalex/WriteiniFile/blob/master/src/WriteiniFile.php#L93 `\n` should be replaced by `PHP_EOL`.

**Comment by al3xLvs** [comment]
Indeed, good remark. You can make a PR if you want.

**Comment by al3xLvs** [comment]
@betterphp I release version 2.0.0 with a fix.

**Comment by betterphp** [comment]
Awesome, thanks :D
